# Generated by Django 6.0.5 on 2026-05-15 15:42

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobopportunity',
            options={},
        ),
        migrations.RemoveField(
            model_name='jobopportunity',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobopportunity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobopportunity',
            name='fetched_at',
        ),
        migrations.RemoveField(
            model_name='jobopportunity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobopportunity',
            name='source',
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='job_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='zoho_id',
            field=models.CharField(default=datetime.datetime(2026, 5, 15, 15, 42, 54, 979156, tzinfo=datetime.timezone.utc), max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='JobAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='JobMatch',
        ),
    ]
