# Generated by Django 6.0.3 on 2026-04-17 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='file',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('revoked', 'Revoked')], default='issued', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
